### ISSUE TITLE
SSLRedirect not working if only TLS is served

### ISSUE THREAD

**Issue by Nhoya** [unrolled/secure#23]
Hello there
i have a problem with `SSLRedirect`, the problem is that i only serve a TLS instance with
`http.ListenAndServeTLS(":8443", "cert.pem", "key.pem", n)`
and no plain istance.

Visiting `localhost:8443` it doesn't redirect me to `https://localhost:8443`
And in console i get
`2017/10/18 17:27:13 http: TLS handshake error from [::1]:39118: tls: first record does not look like a TLS handshake`

There is another solution instead of starting a plain instance?

**Comment by unrolled** [comment]
Hey @Nhoya, so the trick here is that your server is only listening on `:443` right now. The error you are receiving is just saying that request isn't an `https` request. In order to get `http` to redirect to `https` you will need to setup a listener... something simplistic like this might work for you:

```go
go func() {
    http.Serve(l, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        http.Redirect(w, r, "https://"+r.Host+r.RequestURI, http.StatusMovedPermanently)
    }))
}
```

Putting that somewhere before your `http.ListenAndServeTLS` should give you the desired result.

Let me know if this works for you!

**Comment by Nhoya** [comment]
Yea it works as expected @unrolled Thanks for the suggestion! The problem is still that i can't setup a listener on the same port of the SSL instance (of course) Do you know any workaroud for that?

**Comment by unrolled** [comment]
I do not... for localhost testing I usually use 8080 and 8443. Then when it goes out to production it switches to the normal 80 and 443.

I haven't tried this, but it looks like Nginx can do this: https://serverfault.com/questions/47876/handling-http-and-https-requests-using-a-single-port-with-nginx

**Comment by Nhoya** [comment]
Well i want to avoid nginx and use only the binary i ship for web management, thank you very much for the help and explaination.
